export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
}

export const tools: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortName: 'JSON Formatter',
    description: 'Format, validate, and minify JSON with syntax highlighting. All processing happens in your browser.',
    category: 'Formatters',
    icon: '{ }',
    metaTitle: 'JSON Formatter & Validator - SafeTools.dev',
    metaDescription: 'Format, validate, and minify JSON online. Your data never leaves your browser. Free, private, and secure.',
  },
  {
    slug: 'code-beautifier',
    name: 'Code Beautifier',
    shortName: 'Code Beautifier',
    description: 'Beautify and format code in JS, TS, CSS, HTML, JSON, YAML, Markdown, and GraphQL using Prettier.',
    category: 'Formatters',
    icon: '</>',
    metaTitle: 'Code Beautifier - SafeTools.dev',
    metaDescription: 'Beautify and format code in 8+ languages using Prettier. Your data never leaves your browser.',
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    shortName: 'Diff Checker',
    description: 'Compare two texts side-by-side or unified. Highlights additions, deletions, and changes at character, word, or line level.',
    category: 'Comparison',
    icon: '±',
    metaTitle: 'Diff Checker - SafeTools.dev',
    metaDescription: 'Compare text and code differences online. Split or unified view. Your data never leaves your browser.',
  },
  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder / Decoder',
    shortName: 'Base64',
    description: 'Encode and decode Base64 strings and files. Supports text and binary file conversion.',
    category: 'Encoders',
    icon: 'B64',
    metaTitle: 'Base64 Encoder / Decoder - SafeTools.dev',
    metaDescription: 'Encode and decode Base64 online. Supports text and file conversion. Your data never leaves your browser.',
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    shortName: 'URL Encoder',
    description: 'Encode and decode URL components. Handles special characters, query strings, and full URLs.',
    category: 'Encoders',
    icon: '%20',
    metaTitle: 'URL Encoder / Decoder - SafeTools.dev',
    metaDescription: 'Encode and decode URLs and query strings online. Your data never leaves your browser.',
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    shortName: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text or files using the Web Crypto API.',
    category: 'Crypto',
    icon: '#',
    metaTitle: 'Hash Generator - SafeTools.dev',
    metaDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes online. Uses Web Crypto API. Your data never leaves your browser.',
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    shortName: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens. View header, payload, and signature with syntax highlighting.',
    category: 'Crypto',
    icon: 'JWT',
    metaTitle: 'JWT Decoder - SafeTools.dev',
    metaDescription: 'Decode and inspect JWT tokens online. View header, payload, and signature. Your data never leaves your browser.',
  },
  {
    slug: 'color-converter',
    name: 'Color Converter',
    shortName: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and OKLCH formats with a live preview.',
    category: 'Converters',
    icon: '',
    metaTitle: 'Color Converter - SafeTools.dev',
    metaDescription: 'Convert colors between HEX, RGB, HSL, and OKLCH online. Live preview. Your data never leaves your browser.',
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortName: 'Regex Tester',
    description: 'Test regular expressions with real-time matching, capture group highlighting, and flag options.',
    category: 'Testing',
    icon: '.*',
    metaTitle: 'Regex Tester - SafeTools.dev',
    metaDescription: 'Test and debug regular expressions online with real-time matching. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    shortName: 'Markdown Preview',
    description: 'Write and preview GitHub Flavored Markdown in real-time with syntax highlighting and export.',
    category: 'Formatters',
    icon: 'MD',
    metaTitle: 'Markdown Preview - SafeTools.dev',
    metaDescription: 'Write and preview Markdown online with real-time rendering. GFM support. Your data never leaves your browser.',
  },
  {
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript',
    shortName: 'JSON → TS',
    description: 'Generate TypeScript interfaces and types from JSON data automatically.',
    category: 'Converters',
    icon: 'TS',
    metaTitle: 'JSON to TypeScript - SafeTools.dev',
    metaDescription: 'Convert JSON to TypeScript interfaces online. Auto-generate types. Your data never leaves your browser.',
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortName: 'UUID Generator',
    description: 'Generate random UUIDs (v4) with bulk generation, formatting options, and one-click copy.',
    category: 'Generators',
    icon: 'ID',
    metaTitle: 'UUID Generator - SafeTools.dev',
    metaDescription: 'Generate random UUID v4 online. Bulk generation and formatting. Your data never leaves your browser.',
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    shortName: 'Timestamp',
    description: 'Convert between Unix timestamps and human-readable dates. Supports seconds and milliseconds.',
    category: 'Converters',
    icon: '',
    metaTitle: 'Unix Timestamp Converter - SafeTools.dev',
    metaDescription: 'Convert Unix timestamps to dates and dates to timestamps online. Your data never leaves your browser.',
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    shortName: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, PascalCase, kebab-case, UPPER CASE, and more.',
    category: 'Converters',
    icon: 'Aa',
    metaTitle: 'Text Case Converter - SafeTools.dev',
    metaDescription: 'Convert text between camelCase, snake_case, PascalCase and more online. Your data never leaves your browser.',
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortName: 'Lorem Ipsum',
    description: 'Generate placeholder text in paragraphs, sentences, or words with customizable options.',
    category: 'Generators',
    icon: 'Lp',
    metaTitle: 'Lorem Ipsum Generator - SafeTools.dev',
    metaDescription: 'Generate Lorem Ipsum placeholder text online. Paragraphs, sentences, or words. Your data never leaves your browser.',
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortName: 'SQL Formatter',
    description: 'Format and beautify SQL queries with dialect support for PostgreSQL, MySQL, SQLite, and more.',
    category: 'Formatters',
    icon: 'SQL',
    metaTitle: 'SQL Formatter - SafeTools.dev',
    metaDescription: 'Format and beautify SQL queries online. Supports PostgreSQL, MySQL, SQLite and 10+ dialects. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    shortName: 'MD Table',
    description: 'Create Markdown tables visually with a GUI editor. Add rows, columns, set alignment, and copy the generated Markdown.',
    category: 'Generators',
    icon: '▦',
    metaTitle: 'Markdown Table Generator - SafeTools.dev',
    metaDescription: 'Create Markdown tables visually with a GUI editor. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortName: 'MD → HTML',
    description: 'Convert Markdown to HTML with live preview. Supports full document or fragment output with optional minification.',
    category: 'Converters',
    icon: '→H',
    metaTitle: 'Markdown to HTML Converter - SafeTools.dev',
    metaDescription: 'Convert Markdown to HTML online with live preview. Full document or fragment output. Your data never leaves your browser.',
  },
  {
    slug: 'html-to-markdown',
    name: 'HTML to Markdown',
    shortName: 'HTML → MD',
    description: 'Convert HTML to Markdown with GFM support. Configure heading style, code block fences, and bullet characters.',
    category: 'Converters',
    icon: '→M',
    metaTitle: 'HTML to Markdown Converter - SafeTools.dev',
    metaDescription: 'Convert HTML to Markdown online with GFM table and strikethrough support. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    shortName: 'MD → PDF',
    description: 'Convert Markdown to PDF with customizable page size, margins, and font size. Preview before downloading.',
    category: 'Converters',
    icon: 'PDF',
    metaTitle: 'Markdown to PDF Converter - SafeTools.dev',
    metaDescription: 'Convert Markdown to PDF online with customizable page size and margins. Your data never leaves your browser.',
  },
];

export const categories = [...new Set(tools.map((t) => t.category))];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}
