export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
}

export const tools: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortName: 'JSON Formatter',
    description: 'Format, validate, and minify JSON with syntax highlighting. All processing happens in your browser.',
    category: 'Formatters',
    icon: '{ }',
    metaTitle: 'JSON Formatter & Validator - SafeTools.dev',
    metaDescription: 'Format, validate, and minify JSON online. Your data never leaves your browser. Free, private, and secure.',
  },
  {
    slug: 'code-beautifier',
    name: 'Code Beautifier',
    shortName: 'Code Beautifier',
    description: 'Beautify and format code in JS, TS, CSS, HTML, JSON, YAML, Markdown, and GraphQL using Prettier.',
    category: 'Formatters',
    icon: '</>',
    metaTitle: 'Code Beautifier - SafeTools.dev',
    metaDescription: 'Beautify and format code in 8+ languages using Prettier. Your data never leaves your browser.',
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    shortName: 'Diff Checker',
    description: 'Compare two texts side-by-side or unified. Highlights additions, deletions, and changes at character, word, or line level.',
    category: 'Comparison',
    icon: '±',
    metaTitle: 'Diff Checker - SafeTools.dev',
    metaDescription: 'Compare text and code differences online. Split or unified view. Your data never leaves your browser.',
  },
  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder / Decoder',
    shortName: 'Base64',
    description: 'Encode and decode Base64 strings and files. Supports text and binary file conversion.',
    category: 'Encoders',
    icon: 'B64',
    metaTitle: 'Base64 Encoder / Decoder - SafeTools.dev',
    metaDescription: 'Encode and decode Base64 online. Supports text and file conversion. Your data never leaves your browser.',
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    shortName: 'URL Encoder',
    description: 'Encode and decode URL components. Handles special characters, query strings, and full URLs.',
    category: 'Encoders',
    icon: '%20',
    metaTitle: 'URL Encoder / Decoder - SafeTools.dev',
    metaDescription: 'Encode and decode URLs and query strings online. Your data never leaves your browser.',
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    shortName: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text or files using the Web Crypto API.',
    category: 'Crypto',
    icon: '#',
    metaTitle: 'Hash Generator - SafeTools.dev',
    metaDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes online. Uses Web Crypto API. Your data never leaves your browser.',
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    shortName: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens. View header, payload, and signature with syntax highlighting.',
    category: 'Crypto',
    icon: 'JWT',
    metaTitle: 'JWT Decoder - SafeTools.dev',
    metaDescription: 'Decode and inspect JWT tokens online. View header, payload, and signature. Your data never leaves your browser.',
  },
  {
    slug: 'color-converter',
    name: 'Color Converter',
    shortName: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and OKLCH formats with a live preview.',
    category: 'Converters',
    icon: '',
    metaTitle: 'Color Converter - SafeTools.dev',
    metaDescription: 'Convert colors between HEX, RGB, HSL, and OKLCH online. Live preview. Your data never leaves your browser.',
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortName: 'Regex Tester',
    description: 'Test regular expressions with real-time matching, capture group highlighting, and flag options.',
    category: 'Testing',
    icon: '.*',
    metaTitle: 'Regex Tester - SafeTools.dev',
    metaDescription: 'Test and debug regular expressions online with real-time matching. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    shortName: 'Markdown Preview',
    description: 'Write and preview GitHub Flavored Markdown in real-time with syntax highlighting and export.',
    category: 'Formatters',
    icon: 'MD',
    metaTitle: 'Markdown Preview - SafeTools.dev',
    metaDescription: 'Write and preview Markdown online with real-time rendering. GFM support. Your data never leaves your browser.',
  },
  {
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript',
    shortName: 'JSON → TS',
    description: 'Generate TypeScript interfaces and types from JSON data automatically.',
    category: 'Converters',
    icon: 'TS',
    metaTitle: 'JSON to TypeScript - SafeTools.dev',
    metaDescription: 'Convert JSON to TypeScript interfaces online. Auto-generate types. Your data never leaves your browser.',
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortName: 'UUID Generator',
    description: 'Generate random UUIDs (v4) with bulk generation, formatting options, and one-click copy.',
    category: 'Generators',
    icon: 'ID',
    metaTitle: 'UUID Generator - SafeTools.dev',
    metaDescription: 'Generate random UUID v4 online. Bulk generation and formatting. Your data never leaves your browser.',
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    shortName: 'Timestamp',
    description: 'Convert between Unix timestamps and human-readable dates. Supports seconds and milliseconds.',
    category: 'Converters',
    icon: '',
    metaTitle: 'Unix Timestamp Converter - SafeTools.dev',
    metaDescription: 'Convert Unix timestamps to dates and dates to timestamps online. Your data never leaves your browser.',
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    shortName: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, PascalCase, kebab-case, UPPER CASE, and more.',
    category: 'Converters',
    icon: 'Aa',
    metaTitle: 'Text Case Converter - SafeTools.dev',
    metaDescription: 'Convert text between camelCase, snake_case, PascalCase and more online. Your data never leaves your browser.',
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortName: 'Lorem Ipsum',
    description: 'Generate placeholder text in paragraphs, sentences, or words with customizable options.',
    category: 'Generators',
    icon: 'Lp',
    metaTitle: 'Lorem Ipsum Generator - SafeTools.dev',
    metaDescription: 'Generate Lorem Ipsum placeholder text online. Paragraphs, sentences, or words. Your data never leaves your browser.',
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortName: 'SQL Formatter',
    description: 'Format and beautify SQL queries with dialect support for PostgreSQL, MySQL, SQLite, and more.',
    category: 'Formatters',
    icon: 'SQL',
    metaTitle: 'SQL Formatter - SafeTools.dev',
    metaDescription: 'Format and beautify SQL queries online. Supports PostgreSQL, MySQL, SQLite and 10+ dialects. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    shortName: 'MD Table',
    description: 'Create Markdown tables visually with a GUI editor. Add rows, columns, set alignment, and copy the generated Markdown.',
    category: 'Generators',
    icon: '▦',
    metaTitle: 'Markdown Table Generator - SafeTools.dev',
    metaDescription: 'Create Markdown tables visually with a GUI editor. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortName: 'MD → HTML',
    description: 'Convert Markdown to HTML with live preview. Supports full document or fragment output with optional minification.',
    category: 'Converters',
    icon: '→H',
    metaTitle: 'Markdown to HTML Converter - SafeTools.dev',
    metaDescription: 'Convert Markdown to HTML online with live preview. Full document or fragment output. Your data never leaves your browser.',
  },
  {
    slug: 'html-to-markdown',
    name: 'HTML to Markdown',
    shortName: 'HTML → MD',
    description: 'Convert HTML to Markdown with GFM support. Configure heading style, code block fences, and bullet characters.',
    category: 'Converters',
    icon: '→M',
    metaTitle: 'HTML to Markdown Converter - SafeTools.dev',
    metaDescription: 'Convert HTML to Markdown online with GFM table and strikethrough support. Your data never leaves your browser.',
  },
  {
    slug: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    shortName: 'MD → PDF',
    description: 'Convert Markdown to PDF with customizable page size, margins, and font size. Preview before downloading.',
    category: 'Converters',
    icon: 'PDF',
    metaTitle: 'Markdown to PDF Converter - SafeTools.dev',
    metaDescription: 'Convert Markdown to PDF online with customizable page size and margins. Your data never leaves your browser.',
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    shortName: 'Password Gen',
    description: 'Generate strong, random passwords with customizable length, character types, and strength indicator.',
    category: 'Generators',
    icon: '***',
    metaTitle: 'Password Generator - SafeTools.dev',
    metaDescription: 'Generate strong random passwords online using Web Crypto API. Customizable length and character sets. Your data never leaves your browser.',
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    shortName: 'QR Code',
    description: 'Generate QR codes from text or URLs with customizable error correction, colors, and size. Download as PNG or SVG.',
    category: 'Generators',
    icon: 'QR',
    metaTitle: 'QR Code Generator - SafeTools.dev',
    metaDescription: 'Generate QR codes online from text or URLs. Customizable colors and error correction. Your data never leaves your browser.',
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    shortName: 'Image Convert',
    description: 'Convert images between PNG, JPEG, and WebP formats with quality control and resize options.',
    category: 'Converters',
    icon: 'IMG',
    metaTitle: 'Image Converter - SafeTools.dev',
    metaDescription: 'Convert images between PNG, JPEG, and WebP online. Quality control and resize. Your data never leaves your browser.',
  },
  {
    slug: 'csv-json-converter',
    name: 'CSV ↔ JSON Converter',
    shortName: 'CSV ↔ JSON',
    description: 'Convert between CSV and JSON formats bidirectionally. Supports custom delimiters and header options.',
    category: 'Converters',
    icon: 'CSV',
    metaTitle: 'CSV to JSON / JSON to CSV Converter - SafeTools.dev',
    metaDescription: 'Convert CSV to JSON and JSON to CSV online. Custom delimiters and RFC 4180 support. Your data never leaves your browser.',
  },
  {
    slug: 'exif-viewer',
    name: 'EXIF Viewer & Stripper',
    shortName: 'EXIF Viewer',
    description: 'View and strip EXIF metadata from images. Remove GPS location, camera info, and other private data.',
    category: 'Crypto',
    icon: 'EX',
    metaTitle: 'EXIF Viewer & Stripper - SafeTools.dev',
    metaDescription: 'View and remove EXIF metadata from images online. Strip GPS, camera info, and private data. Your data never leaves your browser.',
  },
  {
    slug: 'yaml-json-converter',
    name: 'JSON ↔ YAML Converter',
    shortName: 'JSON ↔ YAML',
    description: 'Convert between JSON and YAML formats bidirectionally. Perfect for Kubernetes configs, CI/CD pipelines, and DevOps workflows.',
    category: 'Converters',
    icon: 'YML',
    metaTitle: 'JSON to YAML / YAML to JSON Converter - SafeTools.dev',
    metaDescription: 'Convert JSON to YAML and YAML to JSON online. Perfect for Kubernetes and DevOps. Your data never leaves your browser.',
  },
  {
    slug: 'cron-expression-generator',
    name: 'Cron Expression Generator',
    shortName: 'Cron Generator',
    description: 'Build and test cron expressions with a visual editor. See human-readable descriptions and next run times.',
    category: 'Generators',
    icon: '⏱',
    metaTitle: 'Cron Expression Generator & Tester - SafeTools.dev',
    metaDescription: 'Build and test cron expressions visually with next run times and human-readable descriptions. Your data never leaves your browser.',
  },
  {
    slug: 'toml-json-converter',
    name: 'TOML ↔ JSON Converter',
    shortName: 'TOML ↔ JSON',
    description: 'Convert between TOML and JSON formats. Essential for Rust (Cargo.toml) and Python (pyproject.toml) projects.',
    category: 'Converters',
    icon: 'TML',
    metaTitle: 'TOML to JSON / JSON to TOML Converter - SafeTools.dev',
    metaDescription: 'Convert TOML to JSON and JSON to TOML online. For Cargo.toml and pyproject.toml. Your data never leaves your browser.',
  },
  {
    slug: 'json-schema-generator',
    name: 'JSON Schema Generator & Validator',
    shortName: 'JSON Schema',
    description: 'Generate JSON Schema from sample data and validate JSON against a schema. Supports Draft 7 and 2020-12.',
    category: 'Generators',
    icon: '{}✓',
    metaTitle: 'JSON Schema Generator & Validator - SafeTools.dev',
    metaDescription: 'Generate JSON Schema from data and validate JSON against schemas online. Your data never leaves your browser.',
  },
  {
    slug: 'openapi-viewer',
    name: 'OpenAPI / Swagger Viewer',
    shortName: 'OpenAPI Viewer',
    description: 'Paste an OpenAPI spec (YAML or JSON) and view interactive API documentation with endpoints, parameters, and schemas.',
    category: 'Formatters',
    icon: 'API',
    metaTitle: 'OpenAPI / Swagger Viewer - SafeTools.dev',
    metaDescription: 'View OpenAPI and Swagger specs as interactive API documentation online. Your data never leaves your browser.',
  },
  {
    slug: 'text-encrypt-decrypt',
    name: 'Text Encrypt / Decrypt (AES)',
    shortName: 'Text Encrypt',
    description: 'Encrypt and decrypt text using AES-GCM with the Web Crypto API. Secure client-side encryption with a password.',
    category: 'Crypto',
    icon: '🔐',
    metaTitle: 'Text Encrypt / Decrypt (AES-GCM) - SafeTools.dev',
    metaDescription: 'Encrypt and decrypt text with AES-GCM using Web Crypto API. Zero server contact. Your data never leaves your browser.',
  },
  {
    slug: 'env-editor',
    name: '.env File Viewer & Editor',
    shortName: '.env Editor',
    description: 'Parse, view, edit, and validate .env files with syntax highlighting and secret masking.',
    category: 'Formatters',
    icon: '.env',
    metaTitle: '.env File Viewer & Editor - SafeTools.dev',
    metaDescription: 'View and edit .env files online with secret masking and validation. Your data never leaves your browser.',
  },
  {
    slug: 'ip-subnet-calculator',
    name: 'IP / Subnet Calculator',
    shortName: 'IP Calculator',
    description: 'Calculate CIDR subnets, IP ranges, broadcast addresses, and network masks for IPv4 and IPv6.',
    category: 'Converters',
    icon: 'IP',
    metaTitle: 'IP / Subnet Calculator (CIDR) - SafeTools.dev',
    metaDescription: 'Calculate CIDR subnets, IP ranges, and network masks for IPv4 online. Your data never leaves your browser.',
  },
  {
    slug: 'llm-token-counter',
    name: 'LLM Token Counter',
    shortName: 'Token Counter',
    description: 'Count tokens for GPT-4, GPT-3.5, and other LLM models. Estimate API costs and check context window limits.',
    category: 'Generators',
    icon: 'TKN',
    metaTitle: 'LLM Token Counter - SafeTools.dev',
    metaDescription: 'Count tokens for GPT-4 and LLM models online. Estimate API costs privately. Your data never leaves your browser.',
  },
  {
    slug: 'prompt-formatter',
    name: 'Prompt Template Formatter',
    shortName: 'Prompt Format',
    description: 'Create prompt templates with {{variables}}, fill them in, and manage a library of reusable prompts.',
    category: 'Formatters',
    icon: '💬',
    metaTitle: 'Prompt Template Formatter - SafeTools.dev',
    metaDescription: 'Create and fill prompt templates with variables online. Manage reusable prompts. Your data never leaves your browser.',
  },
  {
    slug: 'cron-explainer',
    name: 'Cron Explainer',
    shortName: 'Cron Explainer',
    description: 'Paste a cron expression to get a human-readable explanation, field-by-field breakdown, and next scheduled run times.',
    category: 'Converters',
    icon: '⏰',
    metaTitle: 'Cron Expression Explainer - SafeTools.dev',
    metaDescription: 'Explain cron expressions in plain English with field breakdown and next run times. Your data never leaves your browser.',
  },
  {
    slug: 'gitignore-builder',
    name: '.gitignore Builder',
    shortName: '.gitignore',
    description: 'Build .gitignore files by selecting from common templates for languages, frameworks, IDEs, and operating systems.',
    category: 'Generators',
    icon: '.gi',
    metaTitle: '.gitignore Builder - SafeTools.dev',
    metaDescription: 'Build .gitignore files from templates for Node, Python, Java, Go, Rust, and more. Your data never leaves your browser.',
  },
  {
    slug: 'json-table-viewer',
    name: 'JSON Table Viewer',
    shortName: 'JSON Table',
    description: 'Visualize JSON arrays as sortable, filterable tables with pagination and CSV export.',
    category: 'Formatters',
    icon: '▤',
    metaTitle: 'JSON Table Viewer - SafeTools.dev',
    metaDescription: 'View JSON arrays as sortable, filterable tables online. Export to CSV. Your data never leaves your browser.',
  },
  {
    slug: 'svg-path-editor',
    name: 'SVG Path Editor',
    shortName: 'SVG Path',
    description: 'Edit SVG path data visually with draggable control points, a live preview canvas, and bidirectional sync.',
    category: 'Generators',
    icon: '⟡',
    metaTitle: 'SVG Path Editor - SafeTools.dev',
    metaDescription: 'Edit SVG path data visually with draggable control points and live preview. Your data never leaves your browser.',
  },
  {
    slug: 'sensitive-data-redactor',
    name: 'Sensitive Data Redactor',
    shortName: 'Redactor',
    description: 'Detect and redact emails, phone numbers, SSNs, credit cards, API keys, and other sensitive data from text.',
    category: 'Crypto',
    icon: '█',
    metaTitle: 'Sensitive Data Redactor - SafeTools.dev',
    metaDescription: 'Detect and redact sensitive data like emails, SSNs, and API keys from text. Your data never leaves your browser.',
  },
  {
    slug: 'metadata-stripper',
    name: 'Image Metadata Stripper',
    shortName: 'Meta Strip',
    description: 'Batch strip EXIF and metadata from multiple images at once. Remove GPS, camera info, and private data.',
    category: 'Crypto',
    icon: '🧹',
    metaTitle: 'Image Metadata Stripper - SafeTools.dev',
    metaDescription: 'Batch strip EXIF metadata from multiple images. Remove GPS and private data. Your data never leaves your browser.',
  },
  {
    slug: 'json-schema-validator',
    name: 'JSON Schema Validator',
    shortName: 'Schema Valid.',
    description: 'Validate JSON data against a JSON Schema with detailed error reporting. Supports Draft 7 and 2020-12.',
    category: 'Testing',
    icon: '✓{}',
    metaTitle: 'JSON Schema Validator - SafeTools.dev',
    metaDescription: 'Validate JSON against JSON Schema online with detailed errors. Draft 7 and 2020-12. Your data never leaves your browser.',
  },
];

export const categories = [...new Set(tools.map((t) => t.category))];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}
