export interface GitignoreTemplate {
  id: string;
  name: string;
  category: 'Languages' | 'Frameworks' | 'IDEs' | 'OS';
  icon: string;
  rules: string[];
}

export const TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'node',
    name: 'Node.js',
    category: 'Languages',
    icon: 'JS',
    rules: [
      'node_modules/',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      '.pnpm-debug.log*',
      'dist/',
      'build/',
      '.env',
      '.env.local',
      '.env.*.local',
      'coverage/',
      '.nyc_output/',
    ],
  },
  {
    id: 'python',
    name: 'Python',
    category: 'Languages',
    icon: 'PY',
    rules: [
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '*.so',
      '.Python',
      'env/',
      'venv/',
      '.venv/',
      'dist/',
      'build/',
      '*.egg-info/',
      '.eggs/',
      '*.egg',
      '.mypy_cache/',
      '.pytest_cache/',
      '.ruff_cache/',
    ],
  },
  {
    id: 'java',
    name: 'Java',
    category: 'Languages',
    icon: 'JV',
    rules: [
      '*.class',
      '*.jar',
      '*.war',
      '*.ear',
      'target/',
      '.gradle/',
      'build/',
      'out/',
      '.settings/',
      '.project',
      '.classpath',
    ],
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Languages',
    icon: 'GO',
    rules: [
      '*.exe',
      '*.exe~',
      '*.dll',
      '*.so',
      '*.dylib',
      '*.test',
      '*.out',
      'vendor/',
      'go.work',
    ],
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Languages',
    icon: 'RS',
    rules: [
      'target/',
      'Cargo.lock',
      '*.rs.bk',
      '*.pdb',
    ],
  },
  {
    id: 'cpp',
    name: 'C/C++',
    category: 'Languages',
    icon: 'C+',
    rules: [
      '*.o',
      '*.obj',
      '*.so',
      '*.dll',
      '*.dylib',
      '*.exe',
      '*.out',
      '*.a',
      '*.lib',
      'build/',
      'cmake-build-*/',
      'CMakeFiles/',
      'CMakeCache.txt',
    ],
  },
  {
    id: 'dotnet',
    name: '.NET/C#',
    category: 'Languages',
    icon: 'C#',
    rules: [
      'bin/',
      'obj/',
      '*.user',
      '*.suo',
      '*.vs/',
      'packages/',
      '*.nupkg',
      'project.lock.json',
    ],
  },
  {
    id: 'ruby',
    name: 'Ruby',
    category: 'Languages',
    icon: 'RB',
    rules: [
      '*.gem',
      '*.rbc',
      '.bundle/',
      'vendor/bundle/',
      'log/',
      'tmp/',
      'coverage/',
      '.byebug_history',
    ],
  },
  {
    id: 'react',
    name: 'React',
    category: 'Frameworks',
    icon: '⚛',
    rules: [
      'node_modules/',
      'build/',
      'dist/',
      '.env.local',
      '.env.development.local',
      '.env.test.local',
      '.env.production.local',
      'coverage/',
    ],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'Frameworks',
    icon: 'NX',
    rules: [
      '.next/',
      'out/',
      'node_modules/',
      '.env*.local',
      '.vercel',
      '*.tsbuildinfo',
      'next-env.d.ts',
    ],
  },
  {
    id: 'django',
    name: 'Django',
    category: 'Frameworks',
    icon: 'DJ',
    rules: [
      '*.pyc',
      '__pycache__/',
      'db.sqlite3',
      'media/',
      'staticfiles/',
      '.env',
      'venv/',
    ],
  },
  {
    id: 'laravel',
    name: 'Laravel',
    category: 'Frameworks',
    icon: 'LV',
    rules: [
      'vendor/',
      'node_modules/',
      '.env',
      'storage/*.key',
      'public/hot',
      'public/storage',
      'Homestead.json',
      'Homestead.yaml',
    ],
  },
  {
    id: 'vscode',
    name: 'VS Code',
    category: 'IDEs',
    icon: 'VS',
    rules: [
      '.vscode/*',
      '!.vscode/settings.json',
      '!.vscode/tasks.json',
      '!.vscode/launch.json',
      '!.vscode/extensions.json',
      '*.code-workspace',
    ],
  },
  {
    id: 'jetbrains',
    name: 'JetBrains',
    category: 'IDEs',
    icon: 'JB',
    rules: [
      '.idea/',
      '*.iml',
      '*.iws',
      '*.ipr',
      'out/',
      'cmake-build-*/',
    ],
  },
  {
    id: 'vim',
    name: 'Vim',
    category: 'IDEs',
    icon: 'VI',
    rules: [
      '[._]*.s[a-v][a-z]',
      '[._]*.sw[a-p]',
      '[._]s[a-rt-v][a-z]',
      '[._]ss[a-gi-z]',
      '[._]sw[a-p]',
      'Session.vim',
      'Sessionx.vim',
      '.netrwhist',
      '*~',
      'tags',
    ],
  },
  {
    id: 'emacs',
    name: 'Emacs',
    category: 'IDEs',
    icon: 'EM',
    rules: [
      '*~',
      '\\#*\\#',
      '/.emacs.desktop',
      '/.emacs.desktop.lock',
      '*.elc',
      'auto-save-list',
      '.org-id-locations',
      '*_archive',
    ],
  },
  {
    id: 'macos',
    name: 'macOS',
    category: 'OS',
    icon: '🍎',
    rules: [
      '.DS_Store',
      '.AppleDouble',
      '.LSOverride',
      '._*',
      '.Spotlight-V100',
      '.Trashes',
      'Icon\\r',
    ],
  },
  {
    id: 'windows',
    name: 'Windows',
    category: 'OS',
    icon: '🪟',
    rules: [
      'Thumbs.db',
      'Thumbs.db:encryptable',
      'ehthumbs.db',
      'ehthumbs_vista.db',
      '*.lnk',
      'desktop.ini',
      '$RECYCLE.BIN/',
    ],
  },
  {
    id: 'linux',
    name: 'Linux',
    category: 'OS',
    icon: '🐧',
    rules: [
      '*~',
      '.fuse_hidden*',
      '.directory',
      '.Trash-*',
      '.nfs*',
    ],
  },
];
